### ISSUE TITLE
Failure to link interp2dtest to MacPorts gsl

### ISSUE THREAD

**Issue by bkraessig** [diazona/interp2d#7]
The cmake installation of interp2d on my Mac completed only partially. The static library was built successfully, but the linking of the `interp2dtest` failed:

    [ 71%] Built target interp2d_static
    [ 85%] Linking C executable interp2dtest
    ld: library not found for -lgsl
    collect2: error: ld returned 1 exit status
    make[2]: *** [interp2dtest] Error 1
    make[1]: *** [CMakeFiles/interp2dtest.dir/all] Error 2
    make: *** [all] Error 2

The `CMakeCache.txt` contains all the necessary entries for gsl:

    GSL_CFLAGS:INTERNAL=-I/opt/local/include
    GSL_FOUND:INTERNAL=1
    GSL_INCLUDEDIR:INTERNAL=/opt/local/include
    GSL_INCLUDE_DIRS:INTERNAL=/opt/local/include
    GSL_LDFLAGS:INTERNAL=-L/opt/local/lib;-lgsl;-lgslcblas;-lm
    GSL_LIBDIR:INTERNAL=/opt/local/lib
    GSL_LIBRARIES:INTERNAL=gsl;gslcblas;m
    GSL_LIBRARY_DIRS:INTERNAL=/opt/local/lib

I wonder whether this info didn't trickle down into the link command for `interp2dtest`.

**Comment by diazona** [comment]
Yep, it took a little while to track down what needed to be done, but I'd omitted the command to add the directory to the linker search path. It works for me now. Check out commit 59e80385c8d2fe27e4b021e9431e7ff3e7016478 and let me know whether it fixes the issue for you too.
