### ISSUE TITLE
do you really require equally spaced grids?

### ISSUE THREAD

**Issue by floswald** [diazona/interp2d#8]
hello,

i've just read through the GSL 2.1 manual: https://www.gnu.org/software/gsl/manual/html_node/2D-Introduction-to-Interpolation.html#g_t2D-Introduction-to-Interpolation

where it says that one needs two equally spaced grids x and y to use the functions for 2D interpolation. Is that true? thanks.

**Comment by tbeu** [comment]
Not to my knowledge. What is needed is a regular grid.

**Comment by floswald** [comment]
And by regular grid you mean that there are n points for x, m points for y,
and nm points for z =f(x,y)?

**Comment by tbeu** [comment]
exactly

**Comment by floswald** [comment]
ok that's somewhat reassuring - at least that's how it should work in both
of our minds. I'd like to know for sure though from @diazona ? the GSL doc
is very confusing there.

**Comment by diazona** [comment]
Indeed, the grid does not need to be equally spaced, it only needs to be rectangular. (@tbeu is right; he's worked with this code base at least as much as I have so he knows it very well.) There is actually [one test](https://github.com/diazona/interp2d/blob/master/test.c#L277) which uses this feature.

@floswald I'd suggest sending a message to the GSL mailing list about this. Or if you don't want to, I can do it.

**Comment by floswald** [comment]
ok good stuff. yeah if you don't mind sending that email - i'm not
subscribed.

cheers

**Comment by diazona** [comment]
OK, email sent. I'll continue to follow up on this, but seeing as how this is an issue with GSL, not with interp2d, I'll close it here.
